service: aws-node-express-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  memorySize: 512
  timeout: 10
  region: eu-west-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
